version: '3'

services:
    postgresql:
        image: postgres:12-alpine
        container_name: postgresql
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: app-review-to-chat
        hostname: postgres
        restart: always
        user: root
        volumes: 
            - ./tmp/db:/var/lib/postgresql/data

